### ISSUE TITLE
if that is possible to achieve by caddy module

### ISSUE THREAD

**Issue by Mon-ius** [mholt/conncept#2]
Hi, I am new to caddy2. I would like to achieve my own L4 stream rules in Caddy2. Just wonder, if that is possible to write it via caddy module.

**Comment by mholt** [comment]
What do you mean by "L4 stream rules"?

**Comment by Mon-ius** [comment]
L4 protocol redirect(TCP, etc), like Nginx Stream, OpenResty, and haproxy. Something similar to this repo described.

**Comment by mholt** [comment]
Yes, that's what this module does, but from looking at those options, Project Conncept is more flexible, powerful, and extensible.
