### ISSUE TITLE
use httpolyglot to  Serve http and https connections over the same port

### ISSUE THREAD

**Issue by masx200** [mholt/conncept#3]
use httpolyglot to Serve http and https connections over the same port:

https://github.com/mscdex/httpolyglot

https://github.com/mscdex/httpolyglot/issues/3

https://github.com/lvgithub/blog/blob/master/http_and_https_over_same_port/README.MD

**Comment by mholt** [comment]
You don't need a separate application to serve HTTPS and HTTP on the same port; that's what this Caddy module does already.

Same as #4
